name: Build Rockylinux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build docker image
      run: |
        docker build -t sufs_rockylinux -f docker/Dockerfile.rockylinux .
