name: Build Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install mpich
      run: |
        sudo apt-get update
        sudo apt-get install libmpich-dev

    - name: Install cmake
      run: |
        cd ${{ github.workspace }}
        curl -f -s -S -R -L https://github.com/Kitware/CMake/releases/download/v3.29.2/cmake-3.29.2-Linux-x86_64.tar.gz | tar -zx
        echo "${{ github.workspace }}/cmake-3.29.2-linux-x86_64/bin" >> $GITHUB_PATH

    - name: Fetch dependencies
      run: |
        ./get.sh

    - name: Build
      run: |
        ./build.sh gnu -all
        rm -rf libs/ufslibs/build

    - name: Run
      run: |
        cd run
        sed -i -e 's/NHOURS_FCST=24/NHOURS_FCST=3/g' configuration.sh
        sed -i -e 's/NFHMAX_HF=12/NFHMAX_HF=3/g' configuration.sh
        ./fetch_fix_data.sh
        ./fetch_input_data.sh
        ./run.sh
        ls -l preproc_run
        ls -l model_run
        ls -l post_run
