name: Build Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Set environment
      run: |
        echo "::set-env name=CC::gcc-9"
        echo "::set-env name=CXX::g++-9"
        echo "::set-env name=FC::gfortran-9"
        echo "::set-env name=MPICH_CC::gcc-9"
        echo "::set-env name=MPICH_CXX::g++-9"
        echo "::set-env name=MPICH_FC::gfortran-9"

    - name: Fetch dependencies
      run: ./get.sh

# libs/mpilibs
    - name: Build libs/mpilibs
      run: |
        cd ${GITHUB_WORKSPACE}/libs/mpilibs && ./build.sh gnu
        echo "::set-env name=PATH::${GITHUB_WORKSPACE}/libs/mpilibs/local/mpich3/bin:${PATH}"

# libs/3rdparty
    - name: Build libs/3rdparty
      run: |
        if ./build.sh gnu -3rdparty; then
          cat log_3rdparty
          cat libs/3rdparty/src/log_*
          ls -lR libs/3rdparty/local
        else
          cat log_3rdparty
          for log in libs/3rdparty/src/log_*; do
            if [ -f "$log" ]; then cat $log; fi
          done
          exit 1
        fi

# libs/nceplibs
    - name: Build libs/nceplibs
      run: |
        if ./build.sh gnu -nceplibs; then
          cat log_nceplibs
          cat libs/nceplibs/log_*
          ls -lR libs/nceplibs/local
        else
          cat log_nceplibs
          for log in libs/nceplibs/log_*; do
            if [ -f "$log" ]; then cat $log; fi
          done
          exit 1
        fi

# preproc
    - name: Build preproc
      run: |
        if ./build.sh gnu -preproc; then
          cat log_preproc
        else
          cat log_preproc
          exit 1
        fi

# model
    - name: Build model
      run: |
        if ./build.sh gnu -model; then
          cat log_model
        else
          cat log_model
          exit 1
        fi

# post
    - name: Build post
      run: |
        if ./build.sh gnu -post; then
          cat log_post
        else
          cat log_post
          exit 1
        fi

# run
    - name: Run model
      run: |
        cd run
        sed -i -e 's/NHOURS_FCST=24/NHOURS_FCST=3/g' configuration.sh
        sed -i -e 's/NFHMAX_HF=12/NFHMAX_HF=3/g' configuration.sh
        ./fetch_fix_data.sh
        ./fetch_input_data.sh
        ./run_chgres_cube.sh
        ./run_model.sh
        ./run_post.sh
        ls -l chgres_run
        ls -l model_run
        ls -l post_run
