name: Build CentOS 7

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build docker image
      run: |
        docker build -t sufs_centos7 -f docker/Dockerfile.centos7 .
        docker save sufs_centos7:latest | gzip > sufs_centos7.tar.gz

#    - uses: actions/upload-artifact@v1
#      with:
#        name: sufs_centos7.tar.gz
#        path: sufs_centos7.tar.gz
