name: Build Linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install mpich
      run: |
        sudo apt-get update
        sudo apt-get install libmpich-dev

    - name: Fetch dependencies
      run: ./get.sh

    - name: Build
      run: ./build.sh gnu -all

    - name: Run
      run: |
        cd run
        sed -i -e 's/NHOURS_FCST=24/NHOURS_FCST=3/g' configuration.sh
        sed -i -e 's/NFHMAX_HF=12/NFHMAX_HF=3/g' configuration.sh
        ./fetch_fix_data.sh
        ./fetch_input_data.sh
        ./run.sh
        ls -l preproc_run
        ls -l model_run
        ls -l post_run
